// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks_interactor

import (
	context "context"

	entity "github.com/noffrialdi/auth/internal/usecases/entity"

	mock "github.com/stretchr/testify/mock"

	request "github.com/noffrialdi/auth/internal/handler/api/request"
)

// UserIteractor is an autogenerated mock type for the UserIteractor type
type UserIteractor struct {
	mock.Mock
}

type UserIteractor_Expecter struct {
	mock *mock.Mock
}

func (_m *UserIteractor) EXPECT() *UserIteractor_Expecter {
	return &UserIteractor_Expecter{mock: &_m.Mock}
}

// Signup provides a mock function with given fields: ctx, req
func (_m *UserIteractor) Signup(ctx context.Context, req *request.SignUpRequest) (*entity.SignUpResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Signup")
	}

	var r0 *entity.SignUpResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.SignUpRequest) (*entity.SignUpResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.SignUpRequest) *entity.SignUpResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SignUpResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.SignUpRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserIteractor_Signup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signup'
type UserIteractor_Signup_Call struct {
	*mock.Call
}

// Signup is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.SignUpRequest
func (_e *UserIteractor_Expecter) Signup(ctx interface{}, req interface{}) *UserIteractor_Signup_Call {
	return &UserIteractor_Signup_Call{Call: _e.mock.On("Signup", ctx, req)}
}

func (_c *UserIteractor_Signup_Call) Run(run func(ctx context.Context, req *request.SignUpRequest)) *UserIteractor_Signup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*request.SignUpRequest))
	})
	return _c
}

func (_c *UserIteractor_Signup_Call) Return(respone *entity.SignUpResponse, err error) *UserIteractor_Signup_Call {
	_c.Call.Return(respone, err)
	return _c
}

func (_c *UserIteractor_Signup_Call) RunAndReturn(run func(context.Context, *request.SignUpRequest) (*entity.SignUpResponse, error)) *UserIteractor_Signup_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserIteractor creates a new instance of UserIteractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserIteractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserIteractor {
	mock := &UserIteractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
